language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
matrix:
  fast_finish: true
env:
  global:
    - APPNAME=Cti_DataFlow
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.7.0.2
before_script:
  - composer self-update
  - composer install --prefer-source
script:
  - curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh | bash
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
    - "${APPNAME}-${TRAVIS_TAG}.zip"
    - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
